Document: libleveldb
Title: Debian libleveldb Manual
Author: <insert document author here>
Abstract: This manual describes what libleveldb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libleveldb/libleveldb.sgml.gz

Format: postscript
Files: /usr/share/doc/libleveldb/libleveldb.ps.gz

Format: text
Files: /usr/share/doc/libleveldb/libleveldb.text.gz

Format: HTML
Index: /usr/share/doc/libleveldb/html/index.html
Files: /usr/share/doc/libleveldb/html/*.html
